### ISSUE TITLE
[Bug] TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by Wikinaut** [colorsafe/colorsafe#14]
The decode does not work for me (see next post with the scanned image).

```
colorsafe decode 1.png
Traceback (most recent call last):
  File "/home/benutzer/.local/bin/colorsafe", line 10, in <module>
    sys.exit(main())
  File "/home/benutzer/.local/lib/python2.7/site-packages/colorsafe/cmd.py", line 100, in main
    args.func(args)
  File "/home/benutzer/.local/lib/python2.7/site-packages/colorsafe/cmd.py", line 34, in decode
    "." if args.debug else None  # Save in current directory if debug option is specified
  File "/home/benutzer/.local/lib/python2.7/site-packages/colorsafe/decoder/csdecoder_manager.py", line 61, in __init__
    csFile = ColorSafeImagesDecoder(pages, colorDepth, tmpdir)
  File "/home/benutzer/.local/lib/python2.7/site-packages/colorsafe/decoder/csimages_decoder.py", line 42, in __init__
    bounds = get_data_bounds(page, sectorHeight, sectorWidth, gapSize, page_num, tmpdir)
  File "/home/benutzer/.local/lib/python2.7/site-packages/colorsafe/decoder/csdecoder_getbounds.py", line 18, in get_data_bounds
    bounds = get_bounds(page, tmpdir)
  File "/home/benutzer/.local/lib/python2.7/site-packages/colorsafe/decoder/csdecoder_getbounds.py", line 92, in get_bounds
    clean_vertical_borders = clean_and_infer_borders(vertical_sub_borders_all, False)
  File "/home/benutzer/.local/lib/python2.7/site-packages/colorsafe/decoder/csdecoder_getbounds.py", line 301, in clean_and_infer_borders
    along_diffs_flat = reduce(operator.concat, along_diffs_all)
TypeError: reduce() of empty sequence with no initial value

```

**Comment by Wikinaut** [comment]
![1](https://user-images.githubusercontent.com/1151915/51883534-a2c4b880-2383-11e9-8e56-b450a53f8b53.png)

**Comment by justinbass** [comment]
Your scan has a large border on the bottom and right side, which is probably confusing my rudimentary border-detection. Your scan also has a significant Moiré pattern, so decoding the dots would probably not work.

I'm not actively maintaining this project as I've found interest in another project that achieves the same goal, but is far better funded and maintained. I'll post this on the README eventually, as that project currently has no encoder (only a decoder) and it's not fleshed out - but the schema, decoding, and direction is far better than colorsafe's.

**Comment by Wikinaut** [comment]
@justinbass Moiré, yes, I need a way to laser-printout without dithering (etc.), did not find any hints on the net yet. With PaperBack-cli , I get it working with ```-d 80 -s80``` or ```-d 80 -s100``` options:

### Questions
* What is your printer and scanning equipment?
* What is the other project you are talking about?

**Comment by jeremyworger** [comment]
I second this, what is the other project?
