### ISSUE TITLE
No module named 'decoder'

### ISSUE THREAD

**Issue by VicFic2006** [colorsafe/colorsafe#16]
I'm running python 3.8 on Ubuntu 20.10.
```
vicfic@ubuntu2010:~$ colorsafe encode test.txt
Traceback (most recent call last):
  File "/home/vicfic/.local/bin/colorsafe", line 5, in <module>
    from colorsafe.cmd import main
  File "/home/vicfic/.local/lib/python3.8/site-packages/colorsafe/__init__.py", line 1, in <module>
    from decoder import `ColorSafeDecoder`
ModuleNotFoundError: No module named 'decoder'
```
Should I add something to path? I am not an expert.

**Comment by Halamix2** [comment]
The same problem as #7 : only old Python 2.7 is supported
